# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='pro',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
