# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompaniesApp', '0002_auto_20161113_1721'),
        ('ProjectsApp', '0002_auto_20161113_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CompaniesApp.Company'),
        ),
        migrations.AddField(
            model_name='project',
            name='programmingLanguage',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='speciality',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='yearsOfExperience',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(verbose_name=datetime.datetime(2016, 12, 7, 17, 18, 12, 760319)),
        ),
    ]
