# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0001_initial'),
        ('ProjectsApp', '0003_auto_20161207_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assignedTo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GroupsApp.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(),
        ),
    ]
