# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0005_auto_20161207_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_to',
        ),
    ]
