# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GroupsApp', '0001_initial'),
        ('ProjectsApp', '0006_remove_project_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='GroupsApp.Group'),
        ),
    ]
