# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompaniesApp', '0002_auto_20161113_1721'),
        ('ProjectsApp', '0011_auto_20161208_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='companies',
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CompaniesApp.Company'),
        ),
    ]
