# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0013_project_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='createdBy',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
