# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0014_bookmark_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
