# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0018_project_createdby'),
        ('ProjectsApp', '0015_bookmark_name'),
    ]

    operations = [
    ]
