# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0002_comment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GroupsApp.Group'),
        ),
    ]
