# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 17:31
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0004_comment_comment_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=tinymce.models.HTMLField(),
        ),
    ]
