# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0006_auto_20161126_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_engineer',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='myuser',
            name='about',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='contact_info',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('E', 'Engineer')], default='Student', max_length=1),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_university',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
