# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0008_remove_myuser_user_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_university',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
