# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0010_remove_myuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
