# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0013_myuser_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
