# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0014_myuser_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='full_name',
        ),
    ]
